### ISSUE TITLE
add additional team for resource-types and reusable tasks

### ISSUE THREAD

**Issue by lrstanley** [concourse/governance#83]
Thoughts on adding a new team that can triage things under the resource-type and reusable task repositories?:

https://github.com/concourse/governance/blob/master/teams/maintainers.yml#L51-L76

Looks like there may have been initial thought that it could be beneficial given the above file comments. I'd like to help with triaging on resources/tasks but right now it's only maintainers.

**Comment by taylorsilva** [comment]
Adding a new team sounds fine, as per the comments in that file. Do you have some general goals you'd like the team to accomplish?

And most importantly, team name??!?

**Comment by lrstanley** [comment]
My first through would be similar to `all`, and adjusting it to mention resources/tasks as well as the COC, and making it not include all contributors by default (unless we'd be ok with all contributors having triage permissions for all repos?).

I'm terrible at naming things, but couple of ideas:

If tasks and resources are in one:

- contributor-components

Otherwise:
- contributor-resources
- contributor-tasks

**Comment by taylorsilva** [comment]
Okay, that's starting to make sense, having a team just for all the component stuff. Wondering if that should mean all the resource-types (git, s3, registry-image) as well? Or is that what you were asking initially? 😅 

Feel free to make a PR. We can talk more specifics in there.
